// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/partner/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/partner/ports.go -destination=internal/usecase/partner/mock_test.go -package=partner_test
//

// Package partner_test is a generated GoMock package.
package partner_test

import (
	catalog "avito-kitchen/internal/domain/catalog"
	order "avito-kitchen/internal/domain/order"
	partner "avito-kitchen/internal/usecase/partner"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// ResolveVenueByKeyHash mocks base method.
func (m *MockAPIKeyRepository) ResolveVenueByKeyHash(ctx context.Context, keyHash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveVenueByKeyHash", ctx, keyHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveVenueByKeyHash indicates an expected call of ResolveVenueByKeyHash.
func (mr *MockAPIKeyRepositoryMockRecorder) ResolveVenueByKeyHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveVenueByKeyHash", reflect.TypeOf((*MockAPIKeyRepository)(nil).ResolveVenueByKeyHash), ctx, keyHash)
}

// MockVenueRepository is a mock of VenueRepository interface.
type MockVenueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVenueRepositoryMockRecorder
	isgomock struct{}
}

// MockVenueRepositoryMockRecorder is the mock recorder for MockVenueRepository.
type MockVenueRepositoryMockRecorder struct {
	mock *MockVenueRepository
}

// NewMockVenueRepository creates a new mock instance.
func NewMockVenueRepository(ctrl *gomock.Controller) *MockVenueRepository {
	mock := &MockVenueRepository{ctrl: ctrl}
	mock.recorder = &MockVenueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueRepository) EXPECT() *MockVenueRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVenueRepository) Get(ctx context.Context, id uuid.UUID) (*catalog.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*catalog.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVenueRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVenueRepository)(nil).Get), ctx, id)
}

// UpdateProfile mocks base method.
func (m *MockVenueRepository) UpdateProfile(ctx context.Context, id uuid.UUID, patch partner.VenueProfilePatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockVenueRepositoryMockRecorder) UpdateProfile(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockVenueRepository)(nil).UpdateProfile), ctx, id, patch)
}

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockMenuRepository) CreateItem(ctx context.Context, venueID uuid.UUID, item partner.NewMenuItem) (*catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, venueID, item)
	ret0, _ := ret[0].(*catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockMenuRepositoryMockRecorder) CreateItem(ctx, venueID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockMenuRepository)(nil).CreateItem), ctx, venueID, item)
}

// GetFullMenu mocks base method.
func (m *MockMenuRepository) GetFullMenu(ctx context.Context, venueID uuid.UUID) (partner.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullMenu", ctx, venueID)
	ret0, _ := ret[0].(partner.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullMenu indicates an expected call of GetFullMenu.
func (mr *MockMenuRepositoryMockRecorder) GetFullMenu(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullMenu", reflect.TypeOf((*MockMenuRepository)(nil).GetFullMenu), ctx, venueID)
}

// Sync mocks base method.
func (m *MockMenuRepository) Sync(ctx context.Context, venueID uuid.UUID, categories []partner.MenuSyncCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, venueID, categories)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockMenuRepositoryMockRecorder) Sync(ctx, venueID, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockMenuRepository)(nil).Sync), ctx, venueID, categories)
}

// UpdateAvailability mocks base method.
func (m *MockMenuRepository) UpdateAvailability(ctx context.Context, venueID uuid.UUID, updates []partner.AvailabilityUpdate) ([]catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailability", ctx, venueID, updates)
	ret0, _ := ret[0].([]catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvailability indicates an expected call of UpdateAvailability.
func (mr *MockMenuRepositoryMockRecorder) UpdateAvailability(ctx, venueID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailability", reflect.TypeOf((*MockMenuRepository)(nil).UpdateAvailability), ctx, venueID, updates)
}

// UpdateItem mocks base method.
func (m *MockMenuRepository) UpdateItem(ctx context.Context, venueID, itemID uuid.UUID, patch partner.MenuItemPatch) (*catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, venueID, itemID, patch)
	ret0, _ := ret[0].(*catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockMenuRepositoryMockRecorder) UpdateItem(ctx, venueID, itemID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockMenuRepository)(nil).UpdateItem), ctx, venueID, itemID, patch)
}

// MockRescueOfferRepository is a mock of RescueOfferRepository interface.
type MockRescueOfferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRescueOfferRepositoryMockRecorder
	isgomock struct{}
}

// MockRescueOfferRepositoryMockRecorder is the mock recorder for MockRescueOfferRepository.
type MockRescueOfferRepositoryMockRecorder struct {
	mock *MockRescueOfferRepository
}

// NewMockRescueOfferRepository creates a new mock instance.
func NewMockRescueOfferRepository(ctrl *gomock.Controller) *MockRescueOfferRepository {
	mock := &MockRescueOfferRepository{ctrl: ctrl}
	mock.recorder = &MockRescueOfferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRescueOfferRepository) EXPECT() *MockRescueOfferRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRescueOfferRepository) Cancel(ctx context.Context, venueID, offerID uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, venueID, offerID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRescueOfferRepositoryMockRecorder) Cancel(ctx, venueID, offerID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRescueOfferRepository)(nil).Cancel), ctx, venueID, offerID, now)
}

// Create mocks base method.
func (m *MockRescueOfferRepository) Create(ctx context.Context, o catalog.RescueOffer) (*catalog.RescueOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o)
	ret0, _ := ret[0].(*catalog.RescueOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRescueOfferRepositoryMockRecorder) Create(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRescueOfferRepository)(nil).Create), ctx, o)
}

// List mocks base method.
func (m *MockRescueOfferRepository) List(ctx context.Context, venueID uuid.UUID, activeOnly bool, now time.Time) ([]catalog.RescueOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, venueID, activeOnly, now)
	ret0, _ := ret[0].([]catalog.RescueOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRescueOfferRepositoryMockRecorder) List(ctx, venueID, activeOnly, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRescueOfferRepository)(nil).List), ctx, venueID, activeOnly, now)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// ApplyTransition mocks base method.
func (m *MockOrderRepository) ApplyTransition(ctx context.Context, o *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransition", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyTransition indicates an expected call of ApplyTransition.
func (mr *MockOrderRepositoryMockRecorder) ApplyTransition(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransition", reflect.TypeOf((*MockOrderRepository)(nil).ApplyTransition), ctx, o)
}

// Get mocks base method.
func (m *MockOrderRepository) Get(ctx context.Context, id uuid.UUID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderRepository)(nil).Get), ctx, id)
}

// ListForVenue mocks base method.
func (m *MockOrderRepository) ListForVenue(ctx context.Context, venueID uuid.UUID, status *order.Status, since *time.Time, limit int) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForVenue", ctx, venueID, status, since, limit)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForVenue indicates an expected call of ListForVenue.
func (mr *MockOrderRepositoryMockRecorder) ListForVenue(ctx, venueID, status, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForVenue", reflect.TypeOf((*MockOrderRepository)(nil).ListForVenue), ctx, venueID, status, since, limit)
}
