// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/webhook/publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/webhook/publisher.go -destination=internal/adapter/webhook/mock_test.go -package=webhook_test
//

// Package webhook_test is a generated GoMock package.
package webhook_test

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVenueWebhookLookup is a mock of VenueWebhookLookup interface.
type MockVenueWebhookLookup struct {
	ctrl     *gomock.Controller
	recorder *MockVenueWebhookLookupMockRecorder
	isgomock struct{}
}

// MockVenueWebhookLookupMockRecorder is the mock recorder for MockVenueWebhookLookup.
type MockVenueWebhookLookupMockRecorder struct {
	mock *MockVenueWebhookLookup
}

// NewMockVenueWebhookLookup creates a new mock instance.
func NewMockVenueWebhookLookup(ctrl *gomock.Controller) *MockVenueWebhookLookup {
	mock := &MockVenueWebhookLookup{ctrl: ctrl}
	mock.recorder = &MockVenueWebhookLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueWebhookLookup) EXPECT() *MockVenueWebhookLookupMockRecorder {
	return m.recorder
}

// GetWebhookForOrder mocks base method.
func (m *MockVenueWebhookLookup) GetWebhookForOrder(ctx context.Context, orderID uuid.UUID) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookForOrder", ctx, orderID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetWebhookForOrder indicates an expected call of GetWebhookForOrder.
func (mr *MockVenueWebhookLookupMockRecorder) GetWebhookForOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookForOrder", reflect.TypeOf((*MockVenueWebhookLookup)(nil).GetWebhookForOrder), ctx, orderID)
}
