// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/outbox/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/outbox/ports.go -destination=internal/usecase/outbox/mock_test.go -package=outbox_test
//

// Package outbox_test is a generated GoMock package.
package outbox_test

import (
	outbox "avito-kitchen/internal/usecase/outbox"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FetchDue mocks base method.
func (m *MockRepository) FetchDue(ctx context.Context, now time.Time, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDue", ctx, now, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDue indicates an expected call of FetchDue.
func (mr *MockRepositoryMockRecorder) FetchDue(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDue", reflect.TypeOf((*MockRepository)(nil).FetchDue), ctx, now, limit)
}

// MarkFailed mocks base method.
func (m *MockRepository) MarkFailed(ctx context.Context, eventID uuid.UUID, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, eventID, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockRepositoryMockRecorder) MarkFailed(ctx, eventID, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockRepository)(nil).MarkFailed), ctx, eventID, lastErr)
}

// MarkRetry mocks base method.
func (m *MockRepository) MarkRetry(ctx context.Context, eventID uuid.UUID, nextAttemptAt time.Time, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRetry", ctx, eventID, nextAttemptAt, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRetry indicates an expected call of MarkRetry.
func (mr *MockRepositoryMockRecorder) MarkRetry(ctx, eventID, nextAttemptAt, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRetry", reflect.TypeOf((*MockRepository)(nil).MarkRetry), ctx, eventID, nextAttemptAt, lastErr)
}

// MarkSent mocks base method.
func (m *MockRepository) MarkSent(ctx context.Context, eventID uuid.UUID, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, eventID, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockRepositoryMockRecorder) MarkSent(ctx, eventID, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockRepository)(nil).MarkSent), ctx, eventID, sentAt)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, e outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, e)
}
