// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/order/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/order/ports.go -destination=internal/usecase/order/mock_test.go -package=order_test
//

// Package order_test is a generated GoMock package.
package order_test

import (
	catalog "avito-kitchen/internal/domain/catalog"
	order "avito-kitchen/internal/domain/order"
	order0 "avito-kitchen/internal/usecase/order"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMenuItemLookup is a mock of MenuItemLookup interface.
type MockMenuItemLookup struct {
	ctrl     *gomock.Controller
	recorder *MockMenuItemLookupMockRecorder
	isgomock struct{}
}

// MockMenuItemLookupMockRecorder is the mock recorder for MockMenuItemLookup.
type MockMenuItemLookupMockRecorder struct {
	mock *MockMenuItemLookup
}

// NewMockMenuItemLookup creates a new mock instance.
func NewMockMenuItemLookup(ctrl *gomock.Controller) *MockMenuItemLookup {
	mock := &MockMenuItemLookup{ctrl: ctrl}
	mock.recorder = &MockMenuItemLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuItemLookup) EXPECT() *MockMenuItemLookupMockRecorder {
	return m.recorder
}

// DecrementStock mocks base method.
func (m *MockMenuItemLookup) DecrementStock(ctx context.Context, id uuid.UUID, quantity int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStock", ctx, id, quantity)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementStock indicates an expected call of DecrementStock.
func (mr *MockMenuItemLookupMockRecorder) DecrementStock(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStock", reflect.TypeOf((*MockMenuItemLookup)(nil).DecrementStock), ctx, id, quantity)
}

// Get mocks base method.
func (m *MockMenuItemLookup) Get(ctx context.Context, id uuid.UUID) (*catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMenuItemLookupMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMenuItemLookup)(nil).Get), ctx, id)
}

// GetMany mocks base method.
func (m *MockMenuItemLookup) GetMany(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMany", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockMenuItemLookupMockRecorder) GetMany(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockMenuItemLookup)(nil).GetMany), ctx, ids)
}

// LockForCheckout mocks base method.
func (m *MockMenuItemLookup) LockForCheckout(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]catalog.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockForCheckout", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]catalog.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockForCheckout indicates an expected call of LockForCheckout.
func (mr *MockMenuItemLookupMockRecorder) LockForCheckout(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockForCheckout", reflect.TypeOf((*MockMenuItemLookup)(nil).LockForCheckout), ctx, ids)
}

// MockVenueLookup is a mock of VenueLookup interface.
type MockVenueLookup struct {
	ctrl     *gomock.Controller
	recorder *MockVenueLookupMockRecorder
	isgomock struct{}
}

// MockVenueLookupMockRecorder is the mock recorder for MockVenueLookup.
type MockVenueLookupMockRecorder struct {
	mock *MockVenueLookup
}

// NewMockVenueLookup creates a new mock instance.
func NewMockVenueLookup(ctrl *gomock.Controller) *MockVenueLookup {
	mock := &MockVenueLookup{ctrl: ctrl}
	mock.recorder = &MockVenueLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueLookup) EXPECT() *MockVenueLookupMockRecorder {
	return m.recorder
}

// BumpMenuVersion mocks base method.
func (m *MockVenueLookup) BumpMenuVersion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpMenuVersion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpMenuVersion indicates an expected call of BumpMenuVersion.
func (mr *MockVenueLookupMockRecorder) BumpMenuVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpMenuVersion", reflect.TypeOf((*MockVenueLookup)(nil).BumpMenuVersion), ctx, id)
}

// Get mocks base method.
func (m *MockVenueLookup) Get(ctx context.Context, id uuid.UUID) (*catalog.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*catalog.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVenueLookupMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVenueLookup)(nil).Get), ctx, id)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, o *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, o)
}

// Get mocks base method.
func (m *MockOrderRepository) Get(ctx context.Context, id uuid.UUID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderRepository)(nil).Get), ctx, id)
}

// MockIdempotencyRepository is a mock of IdempotencyRepository interface.
type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockIdempotencyRepositoryMockRecorder is the mock recorder for MockIdempotencyRepository.
type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

// NewMockIdempotencyRepository creates a new mock instance.
func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MockIdempotencyRepository) Claim(ctx context.Context, clientID uuid.UUID, key, requestHash string, expiresAt time.Time) (order0.IdempotencyClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, clientID, key, requestHash, expiresAt)
	ret0, _ := ret[0].(order0.IdempotencyClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockIdempotencyRepositoryMockRecorder) Claim(ctx, clientID, key, requestHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockIdempotencyRepository)(nil).Claim), ctx, clientID, key, requestHash, expiresAt)
}

// LinkOrder mocks base method.
func (m *MockIdempotencyRepository) LinkOrder(ctx context.Context, clientID uuid.UUID, key string, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkOrder", ctx, clientID, key, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkOrder indicates an expected call of LinkOrder.
func (mr *MockIdempotencyRepositoryMockRecorder) LinkOrder(ctx, clientID, key, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkOrder", reflect.TypeOf((*MockIdempotencyRepository)(nil).LinkOrder), ctx, clientID, key, orderID)
}

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockCartRepository) Clear(ctx context.Context, clientID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockCartRepositoryMockRecorder) Clear(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCartRepository)(nil).Clear), ctx, clientID)
}

// Get mocks base method.
func (m *MockCartRepository) Get(ctx context.Context, clientID uuid.UUID) (*order.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clientID)
	ret0, _ := ret[0].(*order.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCartRepositoryMockRecorder) Get(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCartRepository)(nil).Get), ctx, clientID)
}

// Save mocks base method.
func (m *MockCartRepository) Save(ctx context.Context, cart *order.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCartRepositoryMockRecorder) Save(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCartRepository)(nil).Save), ctx, cart)
}
