// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/catalog/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/catalog/ports.go -destination=internal/usecase/catalog/mock_test.go -package=catalog_test
//

// Package catalog_test is a generated GoMock package.
package catalog_test

import (
	catalog "avito-kitchen/internal/domain/catalog"
	catalog0 "avito-kitchen/internal/usecase/catalog"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVenueRepository is a mock of VenueRepository interface.
type MockVenueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVenueRepositoryMockRecorder
	isgomock struct{}
}

// MockVenueRepositoryMockRecorder is the mock recorder for MockVenueRepository.
type MockVenueRepositoryMockRecorder struct {
	mock *MockVenueRepository
}

// NewMockVenueRepository creates a new mock instance.
func NewMockVenueRepository(ctrl *gomock.Controller) *MockVenueRepository {
	mock := &MockVenueRepository{ctrl: ctrl}
	mock.recorder = &MockVenueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueRepository) EXPECT() *MockVenueRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockVenueRepository) GetByID(ctx context.Context, id uuid.UUID) (*catalog.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*catalog.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVenueRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVenueRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockVenueRepository) List(ctx context.Context, filter catalog0.ListVenuesFilter, now time.Time) (catalog0.VenuePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, now)
	ret0, _ := ret[0].(catalog0.VenuePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVenueRepositoryMockRecorder) List(ctx, filter, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVenueRepository)(nil).List), ctx, filter, now)
}

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// GetMenu mocks base method.
func (m *MockMenuRepository) GetMenu(ctx context.Context, venueID uuid.UUID) (catalog0.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenu", ctx, venueID)
	ret0, _ := ret[0].(catalog0.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenu indicates an expected call of GetMenu.
func (mr *MockMenuRepositoryMockRecorder) GetMenu(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenu", reflect.TypeOf((*MockMenuRepository)(nil).GetMenu), ctx, venueID)
}

// GetMenuVersion mocks base method.
func (m *MockMenuRepository) GetMenuVersion(ctx context.Context, venueID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuVersion", ctx, venueID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuVersion indicates an expected call of GetMenuVersion.
func (mr *MockMenuRepositoryMockRecorder) GetMenuVersion(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuVersion", reflect.TypeOf((*MockMenuRepository)(nil).GetMenuVersion), ctx, venueID)
}

// MockRescueOfferRepository is a mock of RescueOfferRepository interface.
type MockRescueOfferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRescueOfferRepositoryMockRecorder
	isgomock struct{}
}

// MockRescueOfferRepositoryMockRecorder is the mock recorder for MockRescueOfferRepository.
type MockRescueOfferRepositoryMockRecorder struct {
	mock *MockRescueOfferRepository
}

// NewMockRescueOfferRepository creates a new mock instance.
func NewMockRescueOfferRepository(ctrl *gomock.Controller) *MockRescueOfferRepository {
	mock := &MockRescueOfferRepository{ctrl: ctrl}
	mock.recorder = &MockRescueOfferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRescueOfferRepository) EXPECT() *MockRescueOfferRepositoryMockRecorder {
	return m.recorder
}

// GetActiveForItems mocks base method.
func (m *MockRescueOfferRepository) GetActiveForItems(ctx context.Context, menuItemIDs []uuid.UUID, now time.Time) (map[uuid.UUID]catalog.RescueOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveForItems", ctx, menuItemIDs, now)
	ret0, _ := ret[0].(map[uuid.UUID]catalog.RescueOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveForItems indicates an expected call of GetActiveForItems.
func (mr *MockRescueOfferRepositoryMockRecorder) GetActiveForItems(ctx, menuItemIDs, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveForItems", reflect.TypeOf((*MockRescueOfferRepository)(nil).GetActiveForItems), ctx, menuItemIDs, now)
}

// ListActiveFeed mocks base method.
func (m *MockRescueOfferRepository) ListActiveFeed(ctx context.Context, cursor string, limit int, now time.Time) (catalog0.RescueOfferFeedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveFeed", ctx, cursor, limit, now)
	ret0, _ := ret[0].(catalog0.RescueOfferFeedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveFeed indicates an expected call of ListActiveFeed.
func (mr *MockRescueOfferRepositoryMockRecorder) ListActiveFeed(ctx, cursor, limit, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveFeed", reflect.TypeOf((*MockRescueOfferRepository)(nil).ListActiveFeed), ctx, cursor, limit, now)
}
